/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {},
    borderWidth: {
      DEFAULT: "1px",
      1: "0.5px",
      2: "2px",
      3: "3px",
      4: "4px",
      6: "6px",
      8: "8px",
    },
    borderRadius: {
      none: "0",
      sm: "0.125rem",
      DEFAULT: "0.25rem",
      md: "0.375rem",
      lg: "0.5rem",
      full: "9999px",
      large: "12px",
      form: "10px",
    },
    fontSize: {
      xs: ".75rem",
      sm: ["12px", "18px"],
      tiny: ".875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: ["25px", "37.5px"],
      "2xl": ["31px", "46.5px"],
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "5rem",
    },
  },
  plugins: [],
};
